Fix where tube methods would be missing when new leader is elected
tarantool/sharded-queue pull request #43
Opened 2021-01-20 12:21 UTC by naimulhaider

Currently the tube methods are registered from the init() method of storage. 

When a new leader is elected, the init() method won't be invoked, and therefore the tube methods would be missing in the new writeable storage instance.

Therefore, the proposed solution is to register the methods through `apply_config` which will be invoked even when leaders are changed.

2021-01-20 14:39 UTC, akudiyar requested changes

2021-01-20 14:39 UTC, akudiyar commented on sharded_queue/storage.lua
> +            local cfg_tubes = cartridge.config_get_readonly('tubes') or {}
Shouldn't we take the latest config being currently applied here?

2021-01-20 14:39 UTC, akudiyar commented on sharded_queue/storage.lua
> +            local cfg_tubes = cartridge.config_get_readonly('tubes') or {}
Take a look at line 79

2021-01-20 14:39 UTC, akudiyar commented on sharded_queue/storage.lua
> +            local cfg_tubes = cartridge.config_get_readonly('tubes') or {}
Also, calling "config_get_redonly" 10 times seems not necessary

2021-01-20 14:39 UTC, akudiyar commented
I suggest adding an integration test for the new behavior.

2021-01-21 10:25 UTC, akudiyar commented
@naimulhaider I like the latest version, btw a test is still needed.

2021-02-15 15:54 UTC, pnvasanth commented
@akudiyar I have added the test cases, please have a look.

2021-02-27 13:00 UTC, akudiyar approved these changes

2021-02-27 13:01 UTC, merged