ci: add GitHub Actions CI
tarantool/sharded-queue pull request #56
Opened 2023-05-31 19:00 UTC by oleg-jukovec

The patch adds CI for GitHub Actions and updates flaky tests.

Closes #53
Closes #18

2023-06-05 11:31 UTC, GRISHNOV approved these changes

2023-06-08 11:46 UTC, better0fdead requested changes
It also would be nice to split commit into 2. 
Add CI and fix flaky tests.

2023-06-08 11:46 UTC, better0fdead commented on .github/workflows/tests.yml
> +      - run: make lint
It would be nice to add names to steps.

2023-06-08 11:46 UTC, better0fdead commented on .github/workflows/tests.yml
> +      - run: make test
It would be nice to add names to steps.

2023-06-08 11:46 UTC, better0fdead commented on .github/workflows/tests.yml
> +      - run: make coverage
It would be nice to add names to steps.

2023-06-08 12:33 UTC, oleg-jukovec commented on .github/workflows/tests.yml
> +      - run: make lint
Added.

2023-06-08 12:34 UTC, oleg-jukovec commented on .github/workflows/tests.yml
> +      - run: make coverage
Added.

2023-06-08 12:34 UTC, oleg-jukovec commented
> It also would be nice to split commit into 2. Add CI and fix flaky tests.

Thank you, done.

2023-06-08 13:56 UTC, better0fdead approved these changes

2023-06-08 14:01 UTC, merged